web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./app:/var/www/app
    - ./default.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
    - mysql

php:
  build: "./docker/php"
  dockerfile: "Dockerfile"
  env_file:
    - ".env"
  volumes:
    - ./app:/var/www/app
  links:
    - mysql

mysql:
  build: "./docker/mysql"
  dockerfile: "Dockerfile"
  env_file:
    - ".env"
  environment:
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  ports:
    - ${MYSQL_PORT}:3306
  volumes:
    - "./data/db/mysql:/var/lib/mysql"